version: '3.4'

services:
  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: elasticsearch-comments
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: kibana:8.10.2
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsearch-comments:9200
    depends_on:
      - elasticsearch
volumes: 
  esdata: