
version: '3.4'

services:
  garthercommentsindexing:
    image: garthercommentsindexing
    build:
      context: .
      dockerfile: src/services/Garther.Comments.Indexing/Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
